export const PERU_LOCATIONS = {
    "Lima": [
        "Cercado de Lima",
        "Ate",
        "Barranco",
        "Breña",
        "Comas",
        "Chorrillos",
        "El Agustino",
        "Jesús María",
        "La Molina",
        "La Victoria",
        "Lince",
        "Los Olivos",
        "Lurigancho",
        "Lurín",
        "Magdalena del Mar",
        "Miraflores",
        "Pachacámac",
        "Pucusana",
        "Pueblo Libre",
        "Puente Piedra",
        "Punta Hermosa",
        "Punta Negra",
        "Rímac",
        "San Bartolo",
        "San Borja",
        "San Isidro",
        "San Juan de Lurigancho",
        "San Juan de Miraflores",
        "San Luis",
        "San Martín de Porres",
        "San Miguel",
        "Santa Anita",
        "Santa María del Mar",
        "Santa Rosa",
        "Santiago de Surco",
        "Surquillo",
        "Villa El Salvador",
        "Villa María del Triunfo"
    ],
    "Arequipa": [
        "Arequipa",
        "Alto Selva Alegre",
        "Cayma",
        "Cerro Colorado",
        "Characato",
        "Chiguata",
        "Jacobo Hunter",
        "La Joya",
        "Mariano Melgar",
        "Miraflores",
        "Mollebaya",
        "Paucarpata",
        "Pocsi",
        "Polobaya",
        "Quequeña",
        "Sabandia",
        "Sachaca",
        "San Juan de Siguas",
        "San Juan de Tarucani",
        "Santa Isabel de Siguas",
        "Santa Rita de Siguas",
        "Socabaya",
        "Tiabaya",
        "Uchumayo",
        "Vitor",
        "Yanahuara",
        "Yarabamba",
        "Yura"
    ],
    "Cusco": [
        "Cusco",
        "Ccorca",
        "Poroy",
        "San Jerónimo",
        "San Sebastián",
        "Santiago",
        "Saylla",
        "Wanchaq"
    ],
    "Trujillo": [
        "Trujillo",
        "El Porvenir",
        "Florencia de Mora",
        "Huanchaco",
        "La Esperanza",
        "Laredo",
        "Moche",
        "Poroto",
        "Salaverry",
        "Simbal",
        "Victor Larco Herrera"
    ],
    "Piura": [
        "Piura",
        "Castilla",
        "Catacaos",
        "Cura Mori",
        "El Tallán",
        "La Arena",
        "La Unión",
        "Las Lomas",
        "Tambo Grande",
        "Veintiseis de Octubre"
    ]
} as const;


export const CITY_CENTER_COORDINATES: Record<City, { lat: number; lng: number }> = {
    "Lima": { lat: -12.046374, lng: -77.042793 },
    "Arequipa": { lat: -16.409047, lng: -71.537451 },
    "Cusco": { lat: -13.531950, lng: -71.967463 },
    "Trujillo": { lat: -8.115990, lng: -79.029980 },
    "Piura": { lat: -5.194490, lng: -80.632820 }
};

export type City = keyof typeof PERU_LOCATIONS;

